### ISSUE TITLE
Is Atlas dead/abandoned?

### ISSUE THREAD

**Issue by sserdyuk** [chrismccord/atlas#22]
Having looked at the timeline and the date of last commit (Aug 18, 2014), I had to ask if @chrismccord and @scrogson chose to put effort into something else and this is a dead end?

**Comment by chrismccord** [comment]
Yes it's long dead. Ecto is what you want.

**Comment by pmontrasio** [comment]
Actually this is 1000 times better than Ecto (much easier to understand and use). Too bad it's dead.

**Comment by chrismccord** [comment]
I disagree. After I learned more about functional programming and separation of concerns, I changed my view on what a data access library should look like. The changes required to make this library properly designed would have made it look just like Ecto, but worse, and without a nice query DSL :) I challenge you to give Ecto a second pass and really take the time to digest some of the new concepts that may not be familiar from where you're coming form.
